### ISSUE TITLE
Erro Tabela

### ISSUE THREAD

**Issue by zandotc** [vanderson139/opencart-cielo#21]
Bom Dia, Utilizo a versão 2.3.0.2
Fiz os procedimentos normais de UP, porém quando vou instalar no Modulos de Pagamento Cielo, dá o erro:
Creio que não foram criadas as tabelas necessárias, você teria o dump SQL para disponibilizar?

Fatal error: Uncaught exception 'Exception' with message 'Error: Table loja.oc_order_cielo' doesn't exist<br />Error No: 1146<br />SELECT COUNT(DISTINCT oc.order_cielo_id) AS total FROM oc_order_cielo oc LEFT JOIN oc_order o ON (oc.pedido_numero = o.order_id) LEFT JOIN oc_customer c ON (o.customer_id = c.customer_id)' in /home/loja/public_html/loja/system/library/db/mysqli.php:40 Stack trace: #0 /home/loja/public_html/loja/system/library/db.php(16): DB\MySQLi->query('SELECT COUNT(DI...', Array) #1 /home/loja/public_html/loja/admin/model/payment/cielo.php(71): DB->query('SELECT COUNT(DI...') #2 [internal function]: ModelPaymentCielo->getTotalTransactions(Array) #3 /home/loja/public_html/loja/system/storage/modification/system/engine/loader.php(178): call_user_func_array(Array, Array) #4 [internal function]: Loader->{closure}(Array, Array) #5 /home/loja/public_html/loja/system/engine/proxy.php(25): call_user_func_array(Object(Closure), Array) #6 /home/loja/public_html/loja/admin/controller/ in /home/loja/public_html/loja/system/library/db/mysqli.php on line 40

**Comment by zandotc** [comment]
Consegui usando:

CREATE TABLE oc_order_cielo (
              order_cielo_id int(11) NOT NULL AUTO_INCREMENT,
              tid varchar(40),
              pan varchar(255),
              status varchar(12),
              pedido_numero varchar(20),
              pedido_valor int(11),
              pedido_moeda int(3),
              pedido_data varchar(19),
              pedido_idioma char(2),
              pagamento_bandeira varchar(20),
              pagamento_produto char(1),
              pagamento_parcelas char(2),
              autenticacao_codigo char(2),
              autenticacao_mensagem varchar(255),
              autenticacao_data varchar(19),
              autenticacao_valor int(11),
              autenticacao_eci char(2),
              autorizacao_codigo char(2),
              autorizacao_mensagem varchar(255),
              autorizacao_data varchar(19),
              autorizacao_valor int(11),
              autorizacao_lr char(2),
              autorizacao_arp varchar(20),
              autorizacao_nsu varchar(20),
              captura_codigo char(2),
              captura_mensagem varchar(255),
              captura_data varchar(19),
              captura_valor int(11),
              cancelamento_codigo char(2),
              cancelamento_mensagem varchar(255),
              cancelamento_data varchar(19),
              cancelamento_valor int(11),
              PRIMARY KEY (order_cielo_id),
              KEY tid (tid)
            ) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
